/**
 * Supabase Storage Adapter Integration Tests
 * 
 * These tests run against a real local Supabase instance and require:
 * - Local Supabase running at localhost:54321
 * - SUPABASE_SERVICE_ROLE_KEY environment variable
 * - Database migrations applied
 * 
 * Run with: npm run test:integration
 */

import { config as loadEnv } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { SupabaseStorageAdapter } from '../supabase';
import type { Database } from '@/lib/database.types';

// Integration jest config does not auto-load env files; without this the
// availability gate below is always false locally and the suite silently
// skips (which is how the live-draft round-trip tests first ran only in CI).
loadEnv({ path: '.env.test.local' });
loadEnv({ path: '.env.local' });
import {
  testLiveDraftStorageCRUD,
  testLiveDraftDataIntegrity,
  testLiveDraftConcurrency
} from './test-utils/storage-test-patterns';

// Check if local Supabase is available for integration tests
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
// Accept both hostname forms — .env.test.local uses 127.0.0.1 while CI uses
// localhost; matching only one silently skipped these tests in the other env.
const SUPABASE_AVAILABLE = !!(
    (SUPABASE_URL?.includes('localhost:54321') || SUPABASE_URL?.includes('127.0.0.1:54321')) &&
    SUPABASE_SERVICE_ROLE_KEY
);

describe('SupabaseStorageAdapter Integration Tests', () => {
  let realSupabase: any;
  let realAdapter: SupabaseStorageAdapter;
  let actualUserId: string; // Will be set dynamically from auth.signUp

  beforeAll(() => {
    if (!SUPABASE_AVAILABLE) {
      console.warn('Skipping Supabase integration tests - local Supabase not available at localhost:54321');
      return;
    }

    console.log('Setting up Supabase integration tests');
    console.log('  URL:', SUPABASE_URL);
    console.log('  Service role key available:', !!SUPABASE_SERVICE_ROLE_KEY);

    // Create real Supabase client for integration tests with service role key
    realSupabase = createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!);
  });

  beforeEach(async () => {
    if (!SUPABASE_AVAILABLE || !realSupabase) return;
    
    console.log('🔧 Setting up test user following app signup pattern');
    
    try {
      // Follow the app's user creation pattern: use auth.signUp to create user
      const { data: authData, error: authError } = await realSupabase.auth.signUp({
        email: `test-${Date.now()}@integration.local`, // Unique email to avoid conflicts
        password: 'integration-test-password-123'
      });
      
      if (authError) {
        console.error('❌ Auth signup failed:', authError);
        throw authError;
      }
      
      if (!authData.user) {
        throw new Error('No user returned from auth.signUp');
      }
      
      // Store the actual user ID generated by Supabase Auth
      actualUserId = authData.user.id;
      console.log('✅ Test user created via auth.signUp:', actualUserId);
      
      // Create the application user record (mimicking ensureUserRecord from auth context)
      const { data, error } = await realSupabase.from('users').upsert({
        id: actualUserId,
        email: authData.user.email,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      });
      
      if (error) {
        console.error('❌ User record creation failed:', error);
        throw error;
      }
      
      console.log('✅ User record created successfully');
      
      // Create the storage adapter with the actual user ID
      realAdapter = new SupabaseStorageAdapter(realSupabase, actualUserId, {
        retryConfig: { maxRetries: 1, backoffMs: 50 }
      });
      
      console.log('✅ Storage adapter created for user:', actualUserId);
      
    } catch (error) {
      console.error('❌ Test user setup exception:', error);
      throw error;
    }
  });

  afterEach(async () => {
    if (!SUPABASE_AVAILABLE || !realSupabase || !actualUserId) return;
    
    try {
      console.log(`🧹 Cleaning up test data for user: ${actualUserId}`);
      
      // Clean up test data in reverse dependency order using service role permissions
      await realSupabase.from('live_draft_picks').delete().like('live_draft_id', '%');
      await realSupabase.from('live_draft_teams').delete().like('live_draft_id', '%');
      await realSupabase.from('live_drafts').delete().eq('user_id', actualUserId);
      await realSupabase.from('cost_adjustments').delete().like('draft_session_id', '%');
      await realSupabase.from('player_selections').delete().like('draft_session_id', '%');
      await realSupabase.from('draft_settings').delete().like('draft_session_id', '%');
      await realSupabase.from('draft_sessions').delete().eq('user_id', actualUserId);
      await realSupabase.from('leagues').delete().eq('user_id', actualUserId);
      await realSupabase.from('users').delete().eq('id', actualUserId);
      
      // Clean up auth user as well
      await realSupabase.auth.admin.deleteUser(actualUserId);
      
      console.log('✅ Cleanup completed successfully');
    } catch (error) {
      // Ignore cleanup errors - they might be expected if tests failed
      console.warn('⚠️ Cleanup warning:', error);
    }
  });

  describe('Supabase Connection', () => {
    it('should connect to local Supabase instance', async () => {
      if (!SUPABASE_AVAILABLE) {
        console.log('Skipping - Supabase not available');
        expect(true).toBe(true);
        return;
      }

      // Test basic connectivity with simple query
      const { data, error } = await realSupabase
        .from('users')
        .select('count')
        .limit(1);

      expect(error).toBeNull();
      console.log('✅ Successfully connected to local Supabase');
    });
  });

  describe('Live Draft Operations', () => {
    if (SUPABASE_AVAILABLE) {
      it('should perform CRUD operations with real database', async () => {
        console.log('🧪 Running live draft CRUD tests with real Supabase');
        await testLiveDraftStorageCRUD(realAdapter);
        console.log('✅ CRUD tests completed successfully');
      });

      it('should maintain data integrity with real database', async () => {
        console.log('🧪 Running live draft data integrity tests with real Supabase');
        await testLiveDraftDataIntegrity(realAdapter);
        console.log('✅ Data integrity tests completed successfully');
      });

      it('should handle concurrent operations with real database', async () => {
        console.log('🧪 Running live draft concurrency tests with real Supabase');
        await testLiveDraftConcurrency(realAdapter);
        console.log('✅ Concurrency tests completed successfully');
      });
    } else {
      it('should skip integration tests (Supabase not available)', () => {
        console.log('⏭️  Skipping live draft integration tests - Supabase not available');
        console.log('   To run these tests:');
        console.log('   1. Start local Supabase: npm run dev:db');
        console.log('   2. Set SUPABASE_SERVICE_ROLE_KEY in environment');
        console.log('   3. Run: npm test -- supabase.integration');
        expect(true).toBe(true); // Always pass
      });
    }
  });
});