// Re-export types from centralized location for backward compatibility
export {
  CURRENT_MOCKS_SCHEMA_VERSION,
  type StoredDataCurrent,
  type StoredMocksDataCurrent,
  type StoredDraftDataCurrent,
  type StoredData,
  type StoredDataV4,
  type StoredDataV3,
  type StoredMocksDataV4,
  type StoredMocksDataV3,
  type StoredDraftDataV4,
  type StoredDraftDataV3,
  type StoredDataV2,
  type StoredMocksDataV2,
  type StoredDraftDataV2,
  type Rankings,
  type ExponentialCoefficients,
  type DraftAnalysis,
  type MockPlayer,
  type MockPlayerV4,
  type MockPlayerV2,
  type Rank,
  type RankedPlayer,
  type CostEstimatedPlayer,
  type RosterSlot,
  type RosterSelections,
  type SearchSettingsState,
  type EstimationSettingsState,
  type EstimationSettingsStateV4,
  type EstimationSettingsStateV2,
  type Ranking
} from '@/types/storage';
