-- Live Draft Frames Migration
-- Raw ESPN draft-room WebSocket frames ingested from the tap userscript via
-- /api/live-draft-ingest (see design-docs/features/live-draft/
-- espn-draft-room-protocol.md). Frames are opaque protocol text; parsing
-- happens client-side (src/platforms/espn/liveDraftProtocol.ts).

CREATE TABLE live_draft_frames (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    league_id TEXT NOT NULL,  -- Platform league id (ESPN), from the draft-room URL
    capture_id TEXT NOT NULL, -- Random per-socket id generated by the userscript
    seq INTEGER NOT NULL,     -- Monotonic per capture; (user, capture, seq) dedupes retries
    ts TIMESTAMPTZ NOT NULL,  -- Client-reported capture time; analytical only, untrusted
    dir TEXT NOT NULL CHECK (dir IN ('send', 'receive')),
    data TEXT NOT NULL,       -- Raw frame text, stored opaque
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, capture_id, seq)
);

-- Primary read pattern: incremental poll of a user's frames for a league
CREATE INDEX idx_live_draft_frames_poll ON live_draft_frames(user_id, league_id, id);

-- RLS: owners read (and may later clear) their own frames from the browser.
-- There is deliberately NO INSERT policy or grant for authenticated: writes go
-- only through the ingest route, which verifies the per-user ingest token and
-- inserts with the service-role client (bypasses RLS).
ALTER TABLE live_draft_frames ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own live draft frames" ON live_draft_frames
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own live draft frames" ON live_draft_frames
    FOR DELETE USING (auth.uid() = user_id);

-- Table-level grants for the PostgREST API roles. Newer Supabase CLI no longer
-- auto-grants DML to anon/authenticated/service_role on tables created by the
-- `postgres` migration role, so these must be explicit.
GRANT SELECT, DELETE ON live_draft_frames TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON live_draft_frames TO service_role;

COMMENT ON TABLE live_draft_frames IS 'Raw draft-room WebSocket frames ingested from the tap userscript; parsed client-side';
COMMENT ON COLUMN live_draft_frames.seq IS 'Monotonic per capture_id; unique(user_id, capture_id, seq) makes retried ingest batches idempotent';
COMMENT ON COLUMN live_draft_frames.ts IS 'Client-reported capture time — analytical metadata only, never key server logic off it';
